[package]
name = "hello_starknet"
version = "0.1.0"

[[target.starknet-contract]]
sierra = true
# casm = true # needed for snforge

[dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.7.1" }
starknet = ">=2.2.0"

[cairo]
sierra-replace-ids = true